# =============================================================================
# BASE CONFIG – Standardparameter für den Bitunix GRID Bot
# =============================================================================
# Diese Datei dient als Grundlage für alle Coin-spezifischen YAMLs.
# Coin-Configs erben automatisch alle Werte aus dieser Base-Datei
# und überschreiben nur die relevanten Felder (z.B. Preise, Ordergrößen).
# =============================================================================

symbol: "ONDOUSDT"       # Platzhalter, wird in Coin-Config überschrieben

# -----------------------------------------------------------------------------
# ⚙️ TRADING-GRUNDEINSTELLUNGEN
# -----------------------------------------------------------------------------
trading:
  dry_run: true              # true = Simulation ohne echte Orders
  grid_direction: "both"     # "long", "short" oder "both" – Handelsrichtung
  client_id_prefix: "GRID"   # Präfix für Client-Order-IDs (z.B. "GRID_BTC")

# -----------------------------------------------------------------------------
# 📊 GRID-PARAMETER
# -----------------------------------------------------------------------------
grid:
  lower_price: 0.0           # Untere Preisgrenze des Grids (Coin-spezifisch)
  upper_price: 0.0           # Obere Preisgrenze des Grids (Coin-spezifisch)
  grid_levels: 10            # Anzahl der Gitterlinien (ergibt grid_levels + 1 Preisniveaus)
  grid_mode: "arithmetic"    # "arithmetic" oder "geometric" (Preisverteilung)
  min_price_step: 0.0000001  # Minimales Tick-Intervall für Rundungen

  base_order_size: 20        # Grund-Ordergröße (Coin-spezifisch)
  active_rebuy: true         # Nach Fill erneut Order am selben Level platzieren

  tp_mode: "percent"         # "percent" oder "next_grid"
  take_profit_pct: 0.003     # Nur aktiv, wenn tp_mode = "percent"

  sl_mode: "percent"         # "percent", "fixed" oder "none"
  stop_loss_pct: 0.01        # Nur aktiv, wenn sl_mode = "percent"
  stop_loss_price: 1.2       # Nur bei sl_mode = "fixed" aktiv

  rebalance_interval: 300    # Sekunden zwischen automatischem Rebalancing

# -----------------------------------------------------------------------------
# 💸 RISIKOKONFIGURATION UND GEBÜHREN
# -----------------------------------------------------------------------------
risk:
  include_fees: true         # true = Ordergröße berücksichtigt Gebühren
  fee_side: "taker"          # "maker" oder "taker"
  maker_fee_pct: 0.0002      # Gebührensatz für Maker-Orders
  taker_fee_pct: 0.0006      # Gebührensatz für Taker-Orders

# -----------------------------------------------------------------------------
# 💰 MARGIN- UND HEBELKONFIGURATION
# -----------------------------------------------------------------------------
margin:
  mode: "isolated"           # "isolated" oder "cross"
  leverage: 3                # Hebel für diese Strategie
  auto_reduce_only: false    # true = keine neuen Positionen, nur Reduktion

# -----------------------------------------------------------------------------
# 🧩 STRATEGIEVERHALTEN
# -----------------------------------------------------------------------------
strategy:
  entry_on_touch: true       # true = Order beim Preis-Touch platzieren
