# =============================================================================
# BASE CONFIG – Standardparameter für den Bitunix GRID Bot
# =============================================================================
# Diese Datei dient als Grundlage für alle Coin-spezifischen YAMLs.
# Coin-Configs erben automatisch alle Werte aus dieser Base-Datei
# und überschreiben nur die relevanten Felder (z.B. Preise, Ordergrößen).
# =============================================================================

symbol: "ONDOUSDT"       # Platzhalter, wird in Coin-Config überschrieben

# -----------------------------------------------------------------------------
# ⚙️ TRADING-GRUNDEINSTELLUNGEN
# -----------------------------------------------------------------------------
trading:
  dry_run: false              # true = Simulation ohne echte Orders
  grid_direction: "short"    # "long", "short" oder "both" – Handelsrichtung
  client_id_prefix: "GRID"   # Präfix für Client-Order-IDs (z.B. "GRID_BTC")

# -----------------------------------------------------------------------------
# 📊 GRID-PARAMETER
# -----------------------------------------------------------------------------
grid:
  upper_price: 1.1           # Obere Preisgrenze des Grids (Coin-spezifisch)
  lower_price: 1.0           # Untere Preisgrenze des Grids (Coin-spezifisch)
  grid_levels: 2             # Anzahl der Gitterlinien (ergibt grid_levels + 1 Preisniveaus)

  base_order_size: 20        # Grund-Ordergröße (Coin-spezifisch)

  tp_mode: "next_grid"       # "percent" oder "next_grid"
  take_profit_pct: 0.03      # Nur aktiv, wenn tp_mode = "percent"

  sl_mode: "none"            # "percent", "fixed" oder "none"
  stop_loss_pct: 0.01        # Nur aktiv, wenn sl_mode = "percent"
  stop_loss_price: 0.80      # Nur bei sl_mode = "fixed" aktiv

# -----------------------------------------------------------------------------
# 💸 RISIKOKONFIGURATION UND GEBÜHREN
# -----------------------------------------------------------------------------
risk:
  include_fees: false        # true = Ordergröße berücksichtigt Gebühren

# -----------------------------------------------------------------------------
# 💰 MARGIN- UND HEBELKONFIGURATION
# -----------------------------------------------------------------------------
margin:
  leverage: 1                # Hebel für diese Strategie
