# strategies/GRID/logging_config.yaml
# Hierarchisches Logging für Grid Bot

version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s | %(levelname)-8s | %(name)-20s | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s | %(levelname)-8s | %(name)-20s | %(filename)s:%(lineno)d | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/grid_bot.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  # === Bot-Hauptlogik (immer sichtbar) ===
  GridManager:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  GRID-BOT:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  # === Manager (nur Warnungen in Prod) ===
  OrderSync:
    level: WARNING  # ← NEU: weniger Spam
    handlers: [console, file]
    propagate: false
  
  AccountSync:
    level: WARNING  # ← NEU
    handlers: [console, file]
    propagate: false
  
  GridLifecycle:
    level: WARNING  # ← NEU
    handlers: [console, file]
    propagate: false
  
  HedgeManager:
    level: INFO  # Hedge ist wichtig
    handlers: [console, file]
    propagate: false
  
  RiskManager:
    level: WARNING  # ← NEU
    handlers: [console, file]
    propagate: false
  
  GridCalculator:
    level: WARNING  # ← NEU
    handlers: [console, file]
    propagate: false
  
  VirtualOrderManager:
    level: INFO  # Dry-Run wichtig
    handlers: [console, file]
    propagate: false
  
  # === Core Module (sehr leise) ===
  core:
    level: ERROR  # ← Noch stiller
    handlers: [file]
    propagate: false
  
  websockets:
    level: ERROR
    handlers: [file]
    propagate: false
  
  asyncio:
    level: ERROR
    handlers: [file]
    propagate: false

root:
  level: WARNING  # ← NEU: Default WARNING
  handlers: [console, file]